# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 04:25

from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_year', models.IntegerField()),
                ('s_month', models.IntegerField()),
                ('ear_id', models.TextField()),
                ('ear_time', models.TextField()),
                ('ear_longitude', models.TextField()),
                ('ear_latitude', models.TextField()),
                ('ear_scale', models.TextField()),
                ('ear_deep', models.TextField()),
                ('ear_epicenter_pos', models.TextField()),
            ],
            options={
                'db_table': 'ear_info',
            },
        ),
    ]
