# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ear_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='DT_ear_time',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='ear_deep',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='ear_latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='ear_longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='earthquake',
            name='ear_scale',
            field=models.FloatField(),
        ),
    ]
